### ISSUE TITLE
add setting to make quotes visible by default

### ISSUE THREAD

**Issue by b-lov** [catamphetamine/anychan#15]
see issue title. would be great to have the option to see all the quotes by default instead of opening them on click or hover.

<img width="1064" alt="Screenshot 2023-09-07 at 14 39 02" src="https://github.com/catamphetamine/anychan/assets/8249085/e93a9daa-7460-42df-9f0e-1a9a45de8266">

**Comment by catamphetamine** [comment]
Hmm.

Technically, it would be very simple.
But conceptually, would it make sense?

This UI usually mimicks the way "classic" imageboard UI works, and classic imageboard UI only shows a comment ID in such cases.
I thought: why show comment ID if it doesn't provide any context anyway?
That's why it simply shows a row of dots.

I also experimented with "automatically expand autogenerated quotes" but then I noticed that the page content became cluttered and the speed of reading such page became slow.
Before, a user would only read the meaningful (new) content.
After, the user would read both old (repeated) and new content. The noise ratio would be about 50%.
The user wouldn't be able to tell an autogenerated quote from a human-written one, so they'd have to read them all, and the content of quotes, as I've said, is at least half the whole content on a page.

For that reason, my personal opinion is that such feature wouldn't really be reasonable to have.
Rather, it would be counter-productive.

**Comment by b-lov** [comment]
thats true, it would be much more cluttered. that's why i thought about making it a switch in the settings, not the default view.

thats a good point about autogenerated vs. handwritten comments. i guess i'm just looking for a better way to see the references between comments without always having to either expand all the replies to a given comment or hover over the quotes.

but you're right, to show all the quotes or expand everything by default would lead to lots of repeated content. i guess thats just the nature of imageboards vs a system like reddit, which is based on replies from the ground up and where replies can only exist in a hierarchical relation to a comment and not on one big chronological timeline. i have to think about it some more. thanks for your detailed reply.
